namespace GestureRecognition;

public enum Gesture
{
    Grabbing = 0,
    Grip = 1,
    Holy = 2,
    Point = 3,
    Call = 4,
    Three3 = 5,
    Timeout = 6,
    XSign = 7,
    HandHeart = 8,
    HandHeart2 = 9,
    LittleFinger = 10,
    MiddleFinger = 11,
    TakePicture = 12,
    Dislike = 13,
    Fist = 14,
    Four = 15,
    Like = 16,
    Mute = 17,
    OK = 18,
    One = 19,
    Palm = 20,
    Peace = 21,
    PeaceInverted = 22,
    Rock = 23,
    Stop = 24,
    StopInverted = 25,
    Three = 26,
    Three2 = 27,
    TwoUp = 28,
    TwoUpInverted = 29,
    ThreeGun = 30,
    ThumbIndex = 31,
    ThumbIndex2 = 32,
    NoGesture = 33
}